//! Deterministic provider-tool inventory helpers.

use std::path::Path;

use proxima_core::FlavorRegistryFrozen;
use proxima_core::mcp::{McpToolDescriptor, provider_safe_tool_name};
use serde::Serialize;
use serde_json::Value;

use crate::tools::strict_schema::{StrictSchemaError, StrictToolSchema};
use crate::tools::workspace::WorkspaceToolName;

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct ToolInventoryRow {
    pub canonical_name: String,
    pub provider_safe_name: String,
    pub source: &'static str,
    pub schema_root_type: String,
    pub contains_unbounded_json: bool,
    pub strict_compatible: bool,
    pub strict_error: Option<String>,
    pub produces_schema_ids: Vec<String>,
    pub dispatch_target: String,
}

impl ToolInventoryRow {
    #[must_use]
    pub fn registry(tool: &McpToolDescriptor, source: &'static str) -> Self {
        let strict_result = StrictToolSchema::from_schema(&tool.args_schema);
        let strict_error = strict_result.as_ref().err().map(strict_error);
        let contains_unbounded_json = contains_unbounded_json(&tool.args_schema);
        Self {
            canonical_name: tool.name.to_string(),
            provider_safe_name: provider_safe_tool_name(tool.name),
            source,
            schema_root_type: schema_root_type(&tool.args_schema),
            contains_unbounded_json,
            strict_compatible: strict_result.is_ok(),
            strict_error,
            produces_schema_ids: tool
                .produces_schema_ids
                .iter()
                .map(|schema_id| (*schema_id).to_string())
                .collect(),
            dispatch_target: tool.name.to_string(),
        }
    }

    #[must_use]
    pub fn workspace(tool: WorkspaceToolName) -> Self {
        let canonical = tool.canonical().to_string();
        let schema = tool.input_schema();
        let strict_result = StrictToolSchema::from_schema(&schema);
        let strict_error = strict_result.as_ref().err().map(strict_error);
        let contains_unbounded_json = contains_unbounded_json(&schema);
        Self {
            canonical_name: canonical.clone(),
            provider_safe_name: provider_safe_tool_name(&canonical),
            source: "workspace",
            schema_root_type: schema_root_type(&schema),
            contains_unbounded_json,
            strict_compatible: strict_result.is_ok(),
            strict_error,
            produces_schema_ids: Vec::new(),
            dispatch_target: canonical,
        }
    }
}

#[must_use]
pub fn registry_tool_inventory(
    registry: &FlavorRegistryFrozen,
    source: &'static str,
) -> Vec<ToolInventoryRow> {
    sorted_rows(
        registry
            .list_mcp_tools()
            .iter()
            .map(|tool| ToolInventoryRow::registry(tool, source))
            .collect(),
    )
}

#[must_use]
pub fn registry_tool_inventory_for_prefix(
    registry: &FlavorRegistryFrozen,
    prefix: &str,
    source: &'static str,
) -> Vec<ToolInventoryRow> {
    sorted_rows(
        registry
            .list_mcp_tools()
            .iter()
            .filter(|tool| tool.name.starts_with(prefix))
            .map(|tool| ToolInventoryRow::registry(tool, source))
            .collect(),
    )
}

#[must_use]
pub fn workspace_tool_inventory() -> Vec<ToolInventoryRow> {
    sorted_rows(
        [
            WorkspaceToolName::Shell,
            WorkspaceToolName::TextEditor,
            WorkspaceToolName::ListFiles,
        ]
        .into_iter()
        .map(ToolInventoryRow::workspace)
        .collect(),
    )
}

#[must_use]
pub fn render_inventory_checkpoint(
    title: &str,
    command: &str,
    rows: &[ToolInventoryRow],
) -> String {
    let mut out = String::new();
    out.push_str("# ");
    out.push_str(title);
    out.push_str("\n\n");
    out.push_str("Generated by `");
    out.push_str(command);
    out.push_str("`.\n\n");
    out.push_str("| canonical_name | provider_safe_name | source | schema_root_type | contains_unbounded_json | strict_compatible | strict_error | produces_schema_ids | dispatch_target |\n");
    out.push_str("|---|---|---|---|---|---|---|---|---|\n");
    for row in rows {
        out.push_str(&format!(
            "| {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            cell(&row.canonical_name),
            cell(&row.provider_safe_name),
            row.source,
            cell(&row.schema_root_type),
            row.contains_unbounded_json,
            row.strict_compatible,
            cell(row.strict_error.as_deref().unwrap_or("")),
            cell(&row.produces_schema_ids.join("<br>")),
            cell(&row.dispatch_target),
        ));
    }
    out
}

pub fn assert_inventory_checkpoint_is_current(
    rows: &[ToolInventoryRow],
    path: impl AsRef<Path>,
    title: &str,
    command: &str,
) {
    let rendered = render_inventory_checkpoint(title, command, rows);
    let path = path.as_ref();
    let expected = std::fs::read_to_string(path).unwrap_or_default();
    assert_eq!(
        expected,
        rendered,
        "tool strictness inventory checkpoint drifted at {}\n\n{}",
        path.display(),
        rendered
    );
}

pub fn assert_all_tools_strict_compatible(rows: &[ToolInventoryRow]) {
    let failures = rows
        .iter()
        .filter(|row| !row.strict_compatible)
        .map(|row| {
            format!(
                "{}: {}",
                row.canonical_name,
                row.strict_error
                    .as_deref()
                    .unwrap_or("unknown strict-schema error")
            )
        })
        .collect::<Vec<_>>();

    assert!(
        failures.is_empty(),
        "non-strict-compatible tool schemas:\n{}",
        failures.join("\n")
    );
}

#[must_use]
pub fn sorted_rows(mut rows: Vec<ToolInventoryRow>) -> Vec<ToolInventoryRow> {
    rows.sort_by(|left, right| left.canonical_name.cmp(&right.canonical_name));
    rows
}

fn schema_root_type(schema: &Value) -> String {
    match schema.get("type") {
        Some(Value::String(value)) => value.clone(),
        Some(Value::Array(values)) => values
            .iter()
            .filter_map(Value::as_str)
            .collect::<Vec<_>>()
            .join("|"),
        Some(value) => value.to_string(),
        None if schema.is_boolean() => "boolean".to_string(),
        None => "unspecified".to_string(),
    }
}

fn contains_unbounded_json(schema: &Value) -> bool {
    match schema {
        Value::Bool(true) => true,
        Value::Bool(false) | Value::Null | Value::String(_) | Value::Number(_) => false,
        Value::Array(values) => values.iter().any(contains_unbounded_json),
        Value::Object(object) => {
            if object.is_empty() {
                return true;
            }
            if object.get("additionalProperties") == Some(&Value::Bool(true)) {
                return true;
            }
            object
                .iter()
                .filter(|(key, _)| key.as_str() != "$schema" && key.as_str() != "default")
                .any(|(_, value)| contains_unbounded_json(value))
        }
    }
}

fn strict_error(error: &StrictSchemaError) -> String {
    error.to_string()
}

fn cell(value: &str) -> String {
    value
        .replace('|', r"\|")
        .replace('\n', "<br>")
        .replace('\r', "")
}
