//! sqlx → `StorageError` mapping shared by every verb.
//!
//! Policy: reads and writes both classify through [`map_err`] — a
//! serialization failure inside a read transaction is just as
//! `Retryable` as one inside a write, whether or not the path in hand
//! runs a retry loop. [`internal`] is for non-sqlx failures (row
//! conversion, arithmetic) where no sqlx taxonomy applies.

use proxima_core::StorageError;

pub(crate) fn internal(e: impl std::fmt::Display) -> StorageError {
    StorageError::Internal(e.to_string())
}

/// The partial unique index enforcing one F→A Abstraction per source batch.
/// Named once so the mapper below cannot drift from the migration that
/// creates it.
pub(crate) const FTOA_BATCH_EXCLUSIVE_INDEX: &str = "memories_ftoa_batch_exclusive_uidx";

/// Map a sqlx error to a typed `StorageError`, classifying transient
/// deadlock/serialization failures as [`StorageError::Retryable`]. Exposed
/// (via the crate root) so sidecar inserters — including those generated by the
/// exported `pg_sidecar!` macro in flavor crates — classify errors the same way
/// as every other verb, so a deadlock inside a sidecar INSERT is retryable
/// rather than a swallowed `Internal`.
///
/// Postgres's own sentence is forwarded for the constraints this does not
/// recognise, which means an index name can still reach a caller. That is a
/// wider leak than one function can fix — each constraint needs its rule
/// written out — so only the one demonstrably reachable from an agent tool is
/// translated here.
#[must_use]
#[allow(clippy::needless_pass_by_value)]
pub fn map_err(e: sqlx::Error) -> StorageError {
    use sqlx::Error;
    match &e {
        // This arm matches the index by name, so it already knows which rule
        // fired. An index name is part of no contract the caller can see, so
        // the reply states the rule instead of forwarding Postgres's
        // sentence.
        Error::Database(db)
            if db.is_unique_violation() && db.constraint() == Some(FTOA_BATCH_EXCLUSIVE_INDEX) =>
        {
            StorageError::Conflict(
                "this source batch already has an Abstraction from this operator; a \
                 batch consolidates into exactly one Abstraction. Derive over a \
                 different source batch, or supersede the existing Abstraction."
                    .into(),
            )
        }
        Error::Database(db) if db.is_unique_violation() => {
            StorageError::ConstraintViolation(db.message().to_string())
        }
        Error::Database(db) if db.is_check_violation() => {
            StorageError::ConstraintViolation(db.message().to_string())
        }
        // FK violations are caller-facing (referenced row missing / retracted),
        // not a 5xx-shaped internal fault — surface as Conflict.
        Error::Database(db) if db.is_foreign_key_violation() => {
            StorageError::Conflict(db.message().to_string())
        }
        // Deadlock (40P01), serialization failure (40001) and a lock the
        // caller declined to keep waiting for (55P03) are transient: the
        // whole transaction can be re-run. See `with_bounded_retry`.
        Error::Database(db) if is_retryable_sqlstate(db.code().as_deref()) => {
            StorageError::Retryable(db.message().to_string())
        }
        _ => StorageError::Internal(e.to_string()),
    }
}

/// SQLSTATE codes that mark a transient, retry-after-rollback failure.
///
/// `55P03` (`lock_not_available`) is here because it can only be raised
/// where someone set a `lock_timeout`, and setting one is precisely the
/// statement "I would rather come back than wait". Without it, a
/// transaction that gives up on a lock reports a hard failure that no
/// retry loop recognises — which is worse than the unbounded wait the
/// timeout was added to prevent, because at least the wait eventually
/// succeeded.
fn is_retryable_sqlstate(code: Option<&str>) -> bool {
    matches!(code, Some("40P01" | "40001" | "55P03"))
}

/// Whether a sqlx failure is a transient conflict whose transaction is safe
/// to re-run from the beginning.
///
/// The same classification [`map_err`] applies, for a caller that keeps its
/// own error type and therefore never sees a [`StorageError`]. A flavor
/// running a multi-statement scope erase is the case in hand: it takes row
/// locks in an order derived from its own data, a concurrent writer takes
/// `FOR KEY SHARE` in an order derived from its, and no amount of ordering
/// on one side makes the pair acyclic. `40P01` is therefore a normal
/// outcome, not a fault, and the only correct response is to roll back and
/// try again — which is a decision the caller can only make if it can
/// recognise the code. The same goes for `55P03` when that caller has set
/// a `lock_timeout` rather than wait behind a long-lived reader.
#[must_use]
pub fn is_transient_conflict(err: &sqlx::Error) -> bool {
    matches!(err, sqlx::Error::Database(db) if is_retryable_sqlstate(db.code().as_deref()))
}

/// The number of attempts (initial try plus retries) a caller re-running a
/// whole transaction should allow, so every retry loop in the workspace has
/// the same budget.
pub const MAX_TRANSACTION_ATTEMPTS: usize = MAX_STORAGE_ATTEMPTS;

/// Bounded retry budget for [`with_bounded_retry`]: the total number of
/// attempts (initial try + retries) for a transient transaction.
pub(crate) const MAX_STORAGE_ATTEMPTS: usize = 3;

/// Re-run `op` (a full begin→body→commit transaction) up to
/// [`MAX_STORAGE_ATTEMPTS`] times while it fails with
/// [`StorageError::Retryable`]. Any other outcome (including a `Retryable`
/// on the final attempt) is returned as-is.
///
/// `op` must be self-contained: it opens its own transaction each call, so a
/// rolled-back deadlocked attempt leaves no partial state behind.
pub(crate) async fn with_bounded_retry<T, F, Fut>(mut op: F) -> Result<T, StorageError>
where
    F: FnMut() -> Fut,
    Fut: std::future::Future<Output = Result<T, StorageError>>,
{
    let mut attempt = 1;
    loop {
        match op().await {
            Err(StorageError::Retryable(_)) if attempt < MAX_STORAGE_ATTEMPTS => {
                attempt += 1;
            }
            outcome => return outcome,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::{MAX_STORAGE_ATTEMPTS, is_retryable_sqlstate, with_bounded_retry};
    use proxima_core::StorageError;
    use std::cell::Cell;

    #[test]
    fn transient_sqlstates_are_retryable_and_faults_are_not() {
        assert!(is_retryable_sqlstate(Some("40P01")));
        assert!(is_retryable_sqlstate(Some("40001")));
        // A caller that set a lock_timeout asked to come back, not to fail.
        assert!(is_retryable_sqlstate(Some("55P03")));
        // Waiting past a statement_timeout is not the same statement: it
        // says nothing about whether a lock was involved, so re-running
        // blindly would loop on a genuinely slow query.
        assert!(!is_retryable_sqlstate(Some("57014")));
        assert!(!is_retryable_sqlstate(Some("23503")));
        assert!(!is_retryable_sqlstate(Some("23505")));
        assert!(!is_retryable_sqlstate(None));
    }

    #[tokio::test]
    async fn bounded_retry_stops_after_max_attempts() {
        let calls = Cell::new(0usize);
        let result: Result<(), StorageError> = with_bounded_retry(|| {
            calls.set(calls.get() + 1);
            async { Err(StorageError::Retryable("deadlock".into())) }
        })
        .await;
        assert!(matches!(result, Err(StorageError::Retryable(_))));
        assert_eq!(calls.get(), MAX_STORAGE_ATTEMPTS);
    }

    #[tokio::test]
    async fn bounded_retry_returns_first_success() {
        let calls = Cell::new(0usize);
        let result: Result<u8, StorageError> = with_bounded_retry(|| {
            calls.set(calls.get() + 1);
            async {
                if calls.get() < 2 {
                    Err(StorageError::Retryable("deadlock".into()))
                } else {
                    Ok(7)
                }
            }
        })
        .await;
        assert_eq!(result.unwrap(), 7);
        assert_eq!(calls.get(), 2);
    }

    #[tokio::test]
    async fn bounded_retry_does_not_retry_non_retryable() {
        let calls = Cell::new(0usize);
        let result: Result<(), StorageError> = with_bounded_retry(|| {
            calls.set(calls.get() + 1);
            async { Err(StorageError::Conflict("fk".into())) }
        })
        .await;
        assert!(matches!(result, Err(StorageError::Conflict(_))));
        assert_eq!(calls.get(), 1);
    }
}
