[workspace]
resolver = "3"
members = ["core", "bin/proxima-engine", "storage-pg"]

[workspace.package]
edition = "2024"
rust-version = "1.95"
license = "Apache-2.0"
repository = "https://github.com/Aquilo-Solution-S/Proxima"

[workspace.lints.rust]
unsafe_code = "deny"
missing_debug_implementations = "warn"
unused_must_use = "warn"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
module_name_repetitions = "allow"

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v7", "serde"] }
thiserror = "2"
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "macros", "sync"] }
sqlx = { version = "0.8", default-features = false, features = ["runtime-tokio-rustls", "postgres", "uuid", "time", "macros", "migrate"] }
futures-util = { version = "0.3", default-features = false, features = ["std"] }
async-trait = "0.1"
blake3 = "1"
time = { version = "0.3", default-features = false, features = ["serde", "std"] }
