// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	schema: () => typedError<SchemaResponse, ProtocolError>(__TAURI_INVOKE("schema")),
	query: (req: QueryRequest) => typedError<QueryResponse, ProtocolError>(__TAURI_INVOKE("query", { req })),
	eventIngest: (draft: EventDraft) => typedError<EventIngestOutcome, ProtocolError>(__TAURI_INVOKE("event_ingest", { draft })),
	goalWrite: (draft: GoalDraft) => typedError<GoalWriteOutcome, ProtocolError>(__TAURI_INVOKE("goal_write", { draft })),
	/**
	 *  Subscribe — engine returns a `Stream<Item = ChangeEvent>`; we
	 *  spawn a forwarder onto the caller-supplied `Channel<ChangeEvent>`
	 *  so events flow back through Tauri IPC. The handler returns when
	 *  the subscription is established; the stream lifetime is bound to
	 *  the spawned task and ends when storage closes its end (or the JS
	 *  side drops the channel, surfaced as a send error).
	 */
	subscribe: (req: SubscribeRequest, onEvent: Channel<ChangeEvent>) => typedError<null, ProtocolError>(__TAURI_INVOKE("subscribe", { req, onEvent })),
};

/* Types */
export type ChangeEvent = {
	seq: string,
	owner: Owner,
	kind: ChangeEventKind,
};

export type ChangeEventKind = { EntityAppend: {
	entity_kind: EntityKind,
	entity: EntityRef,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	supersedes: EntityRef | null,
} };

export type CitationMappingHint = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
};

export type CitedObjectHint = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	content_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number],
};

export type EntityKind = "Fact" | "Abstraction" | "Perspective" | "Goal";

/**
 *  Endpoint of an Edge or supersedes target. Sum type matching
 *  `change_event` columns: a memory or a goal.
 */
export type EntityRef = ({ Memory: MemoryId }) & { Goal?: never } | ({ Goal: GoalId }) & { Memory?: never };

/**
 *  Subset of docs/14's `ErrorCode` exercised in M1. Additional
 *  variants land with the verbs that raise them.
 */
export type ErrorCode = "AuthRequired" | "Forbidden" | "UnknownSchema" | "AlreadyIngested" | "IdempotencyConflict" | "NotFound" | "Internal";

export type EventDraft = {
	source_id: SourceId,
	source_batch_id: SourceBatchId,
	owner: Owner,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	payload: number[],
	observed_at: string,
	occurred_at: string,
	cited_object: CitedObjectHint,
	citation_mapping: CitationMappingHint,
};

/**
 *  BLAKE3-32 ContentHash of (source_id, owner, payload).
 *  Per docs/07 §"ID types" — events use ContentHash for
 *  re-receipt dedup, not UUIDv7.
 */
export type EventId = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type EventIngestOutcome = {
	event_id: EventId,
	memory_id: MemoryId,
	change_event_seq: string,
	/**
	 *  True iff the same `event_id` was already ingested.
	 *  docs/14 §EventIngest: "replay is silently a no-op."
	 */
	idempotent_replay: boolean,
};

export type GoalAuthorship = "User" | { System: SystemOrigin } | "External";

export type GoalDraft = {
	owner: Owner,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	text: string,
	state: GoalState,
	parent_goal_ids: GoalId[],
	authorship: GoalAuthorship,
	request_id: string,
};

export type GoalId = string;

export type GoalState = "Active" | "Paused" | "Achieved" | "Abandoned";

export type GoalWriteOutcome = {
	goal_id: GoalId,
	change_event_seq: string,
	/**
	 *  True when the same `(owner, request_id)` existed and the
	 *  body matched — see docs/14 §GoalWrite.
	 */
	idempotent_replay: boolean,
};

export type GroupId = string;

export type MemoryId = string;

/**
 *  Snapshot of a memory row. Goal rows have their own shape
 *  (M2+); not modelled here.
 */
export type MemoryRow = {
	id: MemoryId,
	kind: EntityKind,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	owner: Owner,
	/**
	 *  `serde_json` projection of the sidecar row, populated by storage
	 *  at read time. Empty when the schema has no sidecar (M1 in-memory
	 *  store) or when a future identity-only query mode is added.
	 *  Wire-only field — never persisted (docs/07).
	 */
	payload: number[],
};

export type ModelId = string;

export type OperatorId = string;

export type OperatorKind = "AtoGoal";

export type OrgId = string;

/**
 *  Owner carries principal (access scope) and org_id (billing unit).
 *  org_id is NOT part of the access predicate (AGENTS.md invariant 4).
 */
export type Owner = {
	principal: Principal,
	org_id: OrgId,
};

export type PayloadKind = "Fact" | "Abstraction" | "Perspective" | "Goal" | 
/**
 *  Typed sidecar for an edge row, keyed on `edge_id`. See
 *  `EdgePayload` (docs/03 §EdgePayload) and the relation registry
 *  (docs/02 §"Relation registry").
 */
"Edge" | "CitedObject" | "CitationMapping";

export type PersonalityId = string;

/**
 *  BLAKE3-32 hash of personality state for reproducibility.
 *  Same shape as EventId (docs/07 §"ID types").
 */
export type PersonalityStateHash = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type Principal = ({ User: UserId }) & { Group?: never } | ({ Group: GroupId }) & { User?: never };

export type PromptVersion = string;

export type ProtocolError = {
	code: ErrorCode,
	message: string,
	request_id: string | null,
};

/**
 *  One core-generic Query request. Flavor-typed filters
 *  per docs/14 §"Query" land when the first flavor crate
 *  registers a sidecar (M3+).
 */
export type QueryRequest = {
	owner: Owner,
	entity_kind: EntityKind | null,
	schema_id: SchemaId | null,
	supersession: SupersessionStatus,
	limit: number,
};

export type QueryResponse = {
	memories: MemoryRow[],
	/**
	 *  docs/14 §"Cursor & resume" — None when the store has
	 *  not yet recorded any change events.
	 */
	seq_high_water: string | null,
};

export type SchemaId = string;

export type SchemaInfo = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	kind: PayloadKind,
	filter_keys: string[],
	/**
	 *  Sidecar table identifier (qualified, e.g. `proxima_code.code_chunk_v1`)
	 *  when the payload trait declares one; `None` for `Goal`, `CitedObject`,
	 *  and `CitationMapping` payloads which don't participate in F/A/P
	 *  queries.
	 */
	sidecar_table: string | null,
	/**
	 *  Natural-key columns for stateful Fact schemas (docs/03 §Stateful
	 *  Fact schemas). Empty for stateless / non-Fact schemas. Drives the
	 *  head-by-natural-key SQL emission in `Query` heads-only mode.
	 */
	natural_key_columns: string[],
};

export type SchemaResponse = {
	schemas: SchemaInfo[],
};

export type SchemaVersion = number;

/**
 *  UUIDv7, declared by the source at emit time.
 *  See docs/01 §"The contract".
 */
export type SourceBatchId = string;

// Stable identifier of an Event Source. docs/07 §"ID types".
export type SourceId = string;

export type SubscribeRequest = {
	owner: Owner,
	/**
	 *  Resume cursor. Server returns events with `seq > since`.
	 *  `None` means "from the beginning of the change log".
	 */
	since: string | null,
};

export type SupersessionStatus = 
// Heads only — exclude rows that are superseded.
"HeadsOnly" | 
// Include superseded rows.
"IncludeSuperseded";

export type SystemOrigin = ({ Operator: {
	operator_id: OperatorId,
	operator_kind: OperatorKind,
	model_id: ModelId,
	prompt_version: PromptVersion,
	personality_id: PersonalityId,
	personality_state_hash: PersonalityStateHash,
} }) & { Tool?: never } | ({ Tool: {
	tool_id: ToolId,
} }) & { Operator?: never };

export type ToolId = string;

export type UserId = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

