// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	schema: () => typedError<SchemaResponse, ProtocolError>(__TAURI_INVOKE("schema")),
	query: (req: QueryRequest) => typedError<QueryResponse, ProtocolError>(__TAURI_INVOKE("query", { req })),
	eventHistory: (req: EventHistoryRequest) => typedError<EventHistoryResponse, ProtocolError>(__TAURI_INVOKE("event_history", { req })),
	eventIngest: (draft: EventDraft) => typedError<EventIngestOutcome, ProtocolError>(__TAURI_INVOKE("event_ingest", { draft })),
	goalWrite: (draft: GoalDraft) => typedError<GoalWriteOutcome, ProtocolError>(__TAURI_INVOKE("goal_write", { draft })),
	/**
	 *  Subscribe — engine returns a `Stream<Item = ChangeEvent>`; we
	 *  spawn a forwarder onto the caller-supplied `Channel<ChangeEvent>`
	 *  so events flow back through Tauri IPC. The handler returns when
	 *  the subscription is established; the stream lifetime is bound to
	 *  the spawned task and ends when storage closes its end (or the JS
	 *  side drops the channel, surfaced as a send error).
	 */
	subscribe: (req: SubscribeRequest, onEvent: Channel<ChangeEvent>) => typedError<null, ProtocolError>(__TAURI_INVOKE("subscribe", { req, onEvent })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	modelsListLlm: () => typedError<LlmModelRecord[], CommandError>(__TAURI_INVOKE("models_list_llm")),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	modelsListEmbedding: () => typedError<EmbeddingModelRecord[], CommandError>(__TAURI_INVOKE("models_list_embedding")),
	/**
	 *  # Errors
	 *  Returns `CommandError::DuplicateLlmModel` if the model already exists,
	 *  `CommandError::Storage` on database failures.
	 */
	modelsRegisterLlm: (record: LlmModelRecord) => typedError<null, CommandError>(__TAURI_INVOKE("models_register_llm", { record })),
	/**
	 *  # Errors
	 *  Returns `CommandError::DuplicateEmbeddingModel` if the model already exists,
	 *  `CommandError::Storage` on database failures.
	 */
	modelsRegisterEmbedding: (record: EmbeddingModelRecord) => typedError<null, CommandError>(__TAURI_INVOKE("models_register_embedding", { record })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	modelsDeleteLlm: (vendor: string, modelId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("models_delete_llm", { vendor, modelId })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	modelsDeleteEmbedding: (vendor: string, modelId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("models_delete_embedding", { vendor, modelId })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	tierBindingsGet: () => typedError<TierBindings, CommandError>(__TAURI_INVOKE("tier_bindings_get")),
	/**
	 *  # Errors
	 *  Returns `CommandError::InsufficientTierCaps` if the model's caps don't satisfy
	 *  the tier's operator-union requirements, `CommandError::UnknownLlmModel` if the
	 *  model is not registered, or `CommandError::Storage` on database failures.
	 */
	tierBind: (tier: ModelTier, vendor: string, modelId: string) => typedError<null, CommandError>(__TAURI_INVOKE("tier_bind", { tier, vendor, modelId })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	tierUnbind: (tier: ModelTier) => typedError<boolean, CommandError>(__TAURI_INVOKE("tier_unbind", { tier })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	tierRequires: (tier: ModelTier) => typedError<LlmCaps, CommandError>(__TAURI_INVOKE("tier_requires", { tier })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	embeddingActiveGet: () => typedError<{
	vendor: string,
	model_id: string,
} | null, CommandError>(__TAURI_INVOKE("embedding_active_get")),
	/**
	 *  # Errors
	 *  Returns `CommandError::UnknownEmbeddingModel` if the model is not registered,
	 *  `CommandError::Storage` on database failures.
	 */
	embeddingActiveSet: (vendor: string, modelId: string) => typedError<null, CommandError>(__TAURI_INVOKE("embedding_active_set", { vendor, modelId })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	embeddingActiveClear: () => typedError<boolean, CommandError>(__TAURI_INVOKE("embedding_active_clear")),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	reposList: () => typedError<RepoRecordTs[], CommandError>(__TAURI_INVOKE("repos_list")),
	/**
	 *  # Errors
	 *  `InvalidRepoPath` if canonicalize fails, `NotAGitRepo` if `<path>/.git`
	 *  doesn't exist, `DuplicateRepo` on UNIQUE violation, `Storage` otherwise.
	 */
	reposRegister: (path: string, displayName: string | null) => typedError<RepoRecordTs, CommandError>(__TAURI_INVOKE("repos_register", { path, displayName })),
	/**
	 *  # Errors
	 *  `InvalidUuid` if `repo_id` doesn't parse, `Storage` otherwise.
	 */
	reposDelete: (repoId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("repos_delete", { repoId })),
	/**
	 *  # Errors
	 *  `InvalidUuid` if `repo_id` doesn't parse, `UnknownRepo` if the repo
	 *  is not registered for the sentinel owner, `Storage` otherwise.
	 */
	reposErase: (repoId: string) => typedError<RepoEraseReceiptTs, CommandError>(__TAURI_INVOKE("repos_erase", { repoId })),
	/**
	 *  Persist or return the active ingestion run, then kick the driver.
	 * 
	 *  # Errors
	 *  `UnknownRepo` if the repo is not registered; `InvalidUuid` if the id
	 *  does not parse; `Storage` on database failures.
	 */
	repoIngestStart: (repoId: string) => typedError<RepoIngestionRunTs, CommandError>(__TAURI_INVOKE("repo_ingest_start", { repoId })),
	/**
	 *  Return the active ingestion run for a repo, if any.
	 * 
	 *  # Errors
	 *  `InvalidUuid` if the id does not parse; `Storage` on database failures.
	 */
	repoIngestStatus: (repoId: string) => typedError<{
	run_id: string,
	repo_id: string,
	status: RunStatus,
	stage: RunStage,
	commits_emitted: number,
	files_emitted: number,
	chunks_emitted: number,
	chunks_reused: number,
	chunks_tombstoned: number,
	ast_edges_emitted: number,
	abstractions_emitted: number,
	embeddings_landed: number,
	citations_emitted: number,
	error_message: string | null,
	started_at: string,
	updated_at: string,
	finished_at: string | null,
} | null, CommandError>(__TAURI_INVOKE("repo_ingest_status", { repoId })),
	/**
	 *  Subscribe to current run snapshot plus live events for a repo.
	 * 
	 *  # Errors
	 *  `InvalidUuid` if the id does not parse; `Storage` on database failures.
	 */
	repoIngestSubscribe: (repoId: string, onEvent: Channel<RepoIngestEventTs>) => typedError<null, CommandError>(__TAURI_INVOKE("repo_ingest_subscribe", { repoId, onEvent })),
};

/* Types */
export type ChangeEvent = {
	seq: string,
	owner: Owner,
	kind: ChangeEventKind,
};

export type ChangeEventKind = ({ EntityAppend: {
	entity_kind: EntityKind,
	entity: EntityRef,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	supersedes: EntityRef | null,
} }) & { EdgeAppend?: never } | ({ EdgeAppend: {
	edge_id: string,
	relation: string,
	source: EntityRef,
	target: EntityRef,
} }) & { EntityAppend?: never };

export type CitationMappingHint = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
};

export type CitedObjectHint = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	content_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number],
};

/**
 *  Errors returned from settings Tauri commands. Variants flatten
 *  the underlying `SettingsError` / `ConfigError` shapes into
 *  frontend-friendly typed payloads.
 */
export type CommandError = { kind: "storage"; data: {
	message: string,
} } | { kind: "duplicate_llm_model"; data: {
	model_ref: ModelRef,
} } | { kind: "duplicate_embedding_model"; data: {
	model_ref: ModelRef,
} } | { kind: "unknown_llm_model"; data: {
	model_ref: ModelRef,
} } | { kind: "unknown_embedding_model"; data: {
	model_ref: ModelRef,
} } | 
/**
 *  Tier binding's model fails operator-union caps satisfaction.
 *  Returned by `tier_bind` when the engine's required caps for
 *  the tier exceed the bound model's claimed caps.
 */
{ kind: "insufficient_tier_caps"; data: {
	tier: ModelTier,
	model_ref: ModelRef,
} } | 
/**
 *  CHECK constraint violation in PG — signals Rust↔SQL drift.
 *  User can't fix; logs to console and reports as bug.
 */
{ kind: "invariant"; data: {
	message: string,
} } | { kind: "invalid_repo_path"; data: {
	path: string,
	reason: string,
} } | { kind: "not_a_git_repo"; data: {
	path: string,
} } | { kind: "duplicate_repo"; data: {
	canonical_path: string,
} } | { kind: "unknown_repo"; data: {
	repo_id: string,
} } | { kind: "invalid_uuid"; data: {
	value: string,
} };

/**
 *  Which HTTP API shape a runtime model client speaks. Independent
 *  of vendor: most non-Anthropic vendors expose the OpenAI dialect,
 *  so a runtime entry like
 *  `{vendor: "openrouter", dialect: OpenAI, model_id: "anthropic/..."}`
 *  is normal.
 */
export type Dialect = "anthropic" | "openai";

export type EdgeRow = {
	id: string,
	relation: string,
	relation_class: string,
	source: EntityRef,
	target: EntityRef,
	owner: Owner,
	payload: number[],
};

/**
 *  Embedding capability axes. `dim` is the vector size — boot-time
 *  mismatch against the storage migration's vector column is fatal.
 *  `matryoshka` indicates whether the model produces nested-prefix
 *  embeddings (caller may truncate without re-embedding).
 */
export type EmbedCaps = {
	dim: number,
	matryoshka: boolean,
};

// A single embedding model entry.
export type EmbeddingModelRecord = {
	vendor: string,
	model_id: string,
	base_url: string,
	caps: EmbedCaps,
	secret_ref?: string | null,
};

export type EntityKind = "Fact" | "Abstraction" | "Perspective" | "Goal";

/**
 *  Endpoint of an Edge or supersedes target. Sum type matching
 *  `change_event` columns: a memory or a goal.
 */
export type EntityRef = ({ Memory: MemoryId }) & { Goal?: never } | ({ Goal: GoalId }) & { Memory?: never };

/**
 *  Subset of docs/14's `ErrorCode` exercised in M1. Additional
 *  variants land with the verbs that raise them.
 */
export type ErrorCode = "AuthRequired" | "Forbidden" | "UnknownSchema" | "AlreadyIngested" | "IdempotencyConflict" | "NotFound" | "Internal";

export type EventDraft = {
	source_id: SourceId,
	source_batch_id: SourceBatchId,
	owner: Owner,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	payload: number[],
	observed_at: string,
	occurred_at: string,
	cited_object: CitedObjectHint,
	citation_mapping: CitationMappingHint,
};

export type EventHistoryRequest = {
	owner: Owner,
	limit: number,
	before: string | null,
};

export type EventHistoryResponse = {
	events: ChangeEvent[],
	seq_high_water: string | null,
};

/**
 *  BLAKE3-32 ContentHash of (source_id, owner, payload).
 *  Per docs/07 §"ID types" — events use ContentHash for
 *  re-receipt dedup, not UUIDv7.
 */
export type EventId = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type EventIngestOutcome = {
	event_id: EventId,
	memory_id: MemoryId,
	change_event_seq: string,
	/**
	 *  True iff the same `event_id` was already ingested.
	 *  docs/14 §EventIngest: "replay is silently a no-op."
	 */
	idempotent_replay: boolean,
};

export type GoalAuthorship = "User" | { System: SystemOrigin } | "External";

export type GoalDraft = {
	owner: Owner,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	text: string,
	payload: number[],
	state: GoalState,
	parent_goal_ids: GoalId[],
	supersedes_goal_id: GoalId | null,
	authorship: GoalAuthorship,
	request_id: string,
};

export type GoalId = string;

export type GoalRow = {
	id: GoalId,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	owner: Owner,
	text: string,
	state: GoalState,
	parent_goal_ids: GoalId[],
	supersedes: GoalId | null,
	payload: number[],
};

export type GoalState = "Proposed" | "Active" | "Paused" | "Achieved" | "Abandoned" | "Rejected";

export type GoalWriteOutcome = {
	goal_id: GoalId,
	change_event_seq: string,
	/**
	 *  True when the same `(owner, request_id)` existed and the
	 *  body matched — see docs/14 §GoalWrite.
	 */
	idempotent_replay: boolean,
};

export type GroupId = string;

export type IndexReportTs = {
	commits_emitted: number,
	commits_replayed: number,
	files_present_emitted: number,
	files_tombstoned: number,
	chunks_emitted: number,
	chunks_reused: number,
	chunks_tombstoned: number,
};

export type IngestProgressTs = {
	commit_index: number,
	total_commits: number,
	commit_sha: string,
	commits_emitted: number,
	commits_replayed: number,
	chunks_emitted: number,
	chunks_reused: number,
};

/**
 *  LLM capability axes. Operators declare a `requires: LlmCaps` at
 *  registration; runtime config binds a `(vendor, model_id)` to a
 *  tier and validates that the bound model's claimed caps satisfy
 *  the union of operator `requires` for that tier.
 */
export type LlmCaps = {
	tool_use: boolean,
	json_mode: boolean,
	long_context: boolean,
	vision: boolean,
};

// A single LLM model entry.
export type LlmModelRecord = {
	vendor: string,
	model_id: string,
	dialect: Dialect,
	base_url: string,
	caps: LlmCaps,
	secret_ref?: string | null,
};

export type MemoryId = string;

/**
 *  Snapshot of a memory row. Goal rows have their own shape
 *  (M2+); not modelled here.
 */
export type MemoryRow = {
	id: MemoryId,
	kind: EntityKind,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	owner: Owner,
	/**
	 *  CBOR projection of the sidecar row, populated by storage at read
	 *  time. Empty when the schema has no sidecar or when an
	 *  identity-only query mode is added.
	 *  Wire-only field — never persisted (docs/07).
	 */
	payload: number[],
};

export type ModelId = string;

// Reference to a model by `(vendor, model_id)`.
export type ModelRef = {
	vendor: string,
	model_id: string,
};

/**
 *  Coarse routing class for operator declarations. Substrate-fixed —
 *  expansion is a substrate PR per docs/10 §Model tiers.
 */
export type ModelTier = "fast" | "standard" | "deep";

export type OperatorId = string;

export type OperatorKind = "AtoGoal";

export type OrgId = string;

/**
 *  Owner carries principal (access scope) and org_id (billing unit).
 *  org_id is NOT part of the access predicate (AGENTS.md invariant 4).
 */
export type Owner = {
	principal: Principal,
	org_id: OrgId,
};

export type PayloadKind = "Fact" | "Abstraction" | "Perspective" | "Goal" | 
/**
 *  Typed sidecar for an edge row, keyed on `edge_id`. See
 *  `EdgePayload` (docs/03 §EdgePayload) and the relation registry
 *  (docs/02 §"Relation registry").
 */
"Edge" | "CitedObject" | "CitationMapping";

export type PersonalityId = string;

/**
 *  BLAKE3-32 hash of personality state for reproducibility.
 *  Same shape as EventId (docs/07 §"ID types").
 */
export type PersonalityStateHash = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type Principal = ({ User: UserId }) & { Group?: never } | ({ Group: GroupId }) & { User?: never };

export type PromptVersion = string;

export type ProtocolError = {
	code: ErrorCode,
	message: string,
	request_id: string | null,
};

/**
 *  One core-generic Query request. Flavor-typed filters
 *  per docs/14 §"Query" land when the first flavor crate
 *  registers a sidecar (M3+).
 */
export type QueryRequest = {
	owner: Owner,
	entity_kind: EntityKind | null,
	schema_id: SchemaId | null,
	supersession: SupersessionStatus,
	limit: number,
	// Identity-keyed hydration for Subscribe-driven row fetches.
	memory_ids?: MemoryId[],
	goal_ids?: GoalId[],
	edge_ids?: string[],
};

export type QueryResponse = {
	memories: MemoryRow[],
	goals: GoalRow[],
	edges: EdgeRow[],
	/**
	 *  docs/14 §"Cursor & resume" — None when the store has
	 *  not yet recorded any change events.
	 */
	seq_high_water: string | null,
};

export type RepoEraseReceiptTs = {
	repo_id: string,
	completed_at: string,
	facts_deleted: number,
	abstractions_deleted: number,
	edges_deleted: number,
	embeddings_deleted: number,
	events_deleted: number,
	citation_mappings_deleted: number,
	cited_objects_deleted: number,
	source_batches_deleted: number,
	f2a_rows_deleted: number,
	repo_record_deleted: boolean,
};

export type RepoIngestEventTs = { kind: "progress"; data: IngestProgressTs } | { kind: "snapshot"; data: RepoIngestionRunTs } | { kind: "done"; data: IndexReportTs } | { kind: "error"; data: {
	message: string,
} };

export type RepoIngestionRunTs = {
	run_id: string,
	repo_id: string,
	status: RunStatus,
	stage: RunStage,
	commits_emitted: number,
	files_emitted: number,
	chunks_emitted: number,
	chunks_reused: number,
	chunks_tombstoned: number,
	ast_edges_emitted: number,
	abstractions_emitted: number,
	embeddings_landed: number,
	citations_emitted: number,
	error_message: string | null,
	started_at: string,
	updated_at: string,
	finished_at: string | null,
};

export type RepoRecordTs = {
	repo_id: string,
	canonical_path: string,
	display_name: string,
	has_been_polled: boolean,
	last_polled_at: string | null,
	created_at: string,
};

export type RunStage = "starting" | "facts" | "ast_edges" | "f2a" | "embeddings" | "done";

export type RunStatus = "queued" | "running" | "succeeded" | "failed";

export type SchemaId = string;

export type SchemaInfo = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	kind: PayloadKind,
	filter_keys: string[],
	/**
	 *  Sidecar table identifier (qualified, e.g. `proxima_code.code_chunk_v1`)
	 *  when the payload trait declares one; `None` for `Goal`, `CitedObject`,
	 *  and `CitationMapping` payloads which don't participate in F/A/P
	 *  queries.
	 */
	sidecar_table: string | null,
	/**
	 *  Natural-key columns for stateful Fact schemas (docs/03 §Stateful
	 *  Fact schemas). Empty for stateless / non-Fact schemas. Drives the
	 *  head-by-natural-key SQL emission in `Query` heads-only mode.
	 */
	natural_key_columns: string[],
};

export type SchemaResponse = {
	schemas: SchemaInfo[],
};

export type SchemaVersion = number;

/**
 *  UUIDv7, declared by the source at emit time.
 *  See docs/01 §"The contract".
 */
export type SourceBatchId = string;

// Stable identifier of an Event Source. docs/07 §"ID types".
export type SourceId = string;

export type SubscribeRequest = {
	owner: Owner,
	/**
	 *  Resume cursor. Server returns events with `seq > since`.
	 *  `None` means "from the beginning of the change log".
	 */
	since: string | null,
};

export type SupersessionStatus = 
// Heads only — exclude rows that are superseded.
"HeadsOnly" | 
// Include superseded rows.
"IncludeSuperseded";

export type SystemOrigin = ({ Operator: {
	operator_id: OperatorId,
	operator_kind: OperatorKind,
	model_id: ModelId,
	prompt_version: PromptVersion,
	personality_id: PersonalityId,
	personality_state_hash: PersonalityStateHash,
} }) & { Tool?: never } | ({ Tool: {
	tool_id: ToolId,
} }) & { Operator?: never };

// Tier-to-model bindings. Each tier may be unbound (None).
export type TierBindings = {
	fast?: ModelRef | null,
	standard?: ModelRef | null,
	deep?: ModelRef | null,
};

export type ToolId = string;

export type UserId = string;

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

