// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	schema: () => typedError<SchemaResponse, ProtocolError>(__TAURI_INVOKE("schema")),
	query: (req: QueryRequest) => typedError<QueryResponse, ProtocolError>(__TAURI_INVOKE("query", { req })),
	eventHistory: (req: EventHistoryRequest) => typedError<EventHistoryResponse, ProtocolError>(__TAURI_INVOKE("event_history", { req })),
	eventIngest: (draft: EventDraft) => typedError<EventIngestOutcome, ProtocolError>(__TAURI_INVOKE("event_ingest", { draft })),
	goalWrite: (draft: GoalDraft) => typedError<GoalWriteOutcome, ProtocolError>(__TAURI_INVOKE("goal_write", { draft })),
	goalReactivate: (req: GoalReactivateTs) => typedError<EventIngestOutcome, ProtocolError>(__TAURI_INVOKE("goal_reactivate", { req })),
	listPersonalityInstances: (req: ListPersonalityInstancesTs) => typedError<PersonalityInstanceTs[], ProtocolError>(__TAURI_INVOKE("list_personality_instances", { req })),
	listWakeInvocations: (req: ListWakeInvocationsTs) => typedError<WakeInvocationTs[], ProtocolError>(__TAURI_INVOKE("list_wake_invocations", { req })),
	instantiatePersonality: (req: InstantiatePersonalityTs) => typedError<InstantiatePersonalityOutcomeTs, ProtocolError>(__TAURI_INVOKE("instantiate_personality", { req })),
	setWakeEntries: (req: SetWakeEntriesTs) => typedError<SetWakeEntriesOutcomeTs, ProtocolError>(__TAURI_INVOKE("set_wake_entries", { req })),
	tombstonePersonality: (req: TombstonePersonalityTs) => typedError<TombstonePersonalityOutcomeTs, ProtocolError>(__TAURI_INVOKE("tombstone_personality", { req })),
	/**
	 *  Subscribe — engine returns a `Stream<Item = ChangeEvent>`; we
	 *  spawn a forwarder onto the caller-supplied `Channel<ChangeEvent>`
	 *  so events flow back through Tauri IPC. The handler returns when
	 *  the subscription is established; the stream lifetime is bound to
	 *  the spawned task and ends when storage closes its end (or the JS
	 *  side drops the channel, surfaced as a send error).
	 */
	subscribe: (req: SubscribeRequest, onEvent: Channel<ChangeEvent>) => typedError<null, ProtocolError>(__TAURI_INVOKE("subscribe", { req, onEvent })),
	registerInferenceTarget: (req: RegisterInferenceTargetTs) => typedError<RegisterInferenceTargetOutcomeTs, ProtocolError>(__TAURI_INVOKE("register_inference_target", { req })),
	listInferenceTargets: (req: ListInferenceTargetsTs) => typedError<InferenceTargetTs[], ProtocolError>(__TAURI_INVOKE("list_inference_targets", { req })),
	removeInferenceTarget: (req: RemoveInferenceTargetTs) => typedError<RemoveInferenceTargetOutcomeTs, ProtocolError>(__TAURI_INVOKE("remove_inference_target", { req })),
	bindInferenceTier: (req: BindInferenceTierTs) => typedError<null, ProtocolError>(__TAURI_INVOKE("bind_inference_tier", { req })),
	listInferenceTierBindings: (req: ListInferenceTierBindingsTs) => typedError<InferenceTierBindingTs[], ProtocolError>(__TAURI_INVOKE("list_inference_tier_bindings", { req })),
	/**
	 *  # Errors
	 *  Returns `ProtocolError::Internal` when the platform lookup command cannot
	 *  be executed. Missing harness binaries return `Ok(None)`.
	 */
	detectLocalHarness: (name: string) => typedError<{
	path: string,
	version: string,
} | null, ProtocolError>(__TAURI_INVOKE("detect_local_harness", { name })),
	listOwnerRecipes: (req: ListOwnerRecipesTs) => typedError<OwnerRecipesListingTs, ProtocolError>(__TAURI_INVOKE("list_owner_recipes", { req })),
	listBundledRecipes: () => typedError<BundledRecipeTs[], ProtocolError>(__TAURI_INVOKE("list_bundled_recipes")),
	listMcpTools: () => typedError<McpToolTs[], ProtocolError>(__TAURI_INVOKE("list_mcp_tools")),
	listWorkspaceTools: () => typedError<WorkspaceToolTs[], ProtocolError>(__TAURI_INVOKE("list_workspace_tools")),
	listRelations: () => typedError<RelationTs[], ProtocolError>(__TAURI_INVOKE("list_relations")),
	wakeEntryProduces: (substratePalette: string[]) => typedError<ProducesTs, ProtocolError>(__TAURI_INVOKE("wake_entry_produces", { substratePalette })),
	/**
	 *  # Errors
	 *  Returns `CommandError::SecretStore` when the OS keychain cannot be used.
	 */
	mcpConnectionGet: () => typedError<McpConnectionTs, CommandError>(__TAURI_INVOKE("mcp_connection_get")),
	/**
	 *  # Errors
	 *  Returns `CommandError::SecretStore` when the OS keychain cannot be used.
	 */
	mcpMasterTokenRotate: () => typedError<McpConnectionTs, CommandError>(__TAURI_INVOKE("mcp_master_token_rotate")),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	modelsListEmbedding: () => typedError<EmbeddingModelRecord[], CommandError>(__TAURI_INVOKE("models_list_embedding")),
	/**
	 *  # Errors
	 *  Returns `CommandError::DuplicateEmbeddingModel` if the model already exists,
	 *  `CommandError::Storage` on database failures.
	 */
	modelsRegisterEmbedding: (record: EmbeddingModelRecord) => typedError<null, CommandError>(__TAURI_INVOKE("models_register_embedding", { record })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	modelsDeleteEmbedding: (vendor: string, modelId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("models_delete_embedding", { vendor, modelId })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	embeddingActiveGet: () => typedError<{
	vendor: string,
	model_id: string,
} | null, CommandError>(__TAURI_INVOKE("embedding_active_get")),
	/**
	 *  # Errors
	 *  Returns `CommandError::UnknownEmbeddingModel` if the model is not registered,
	 *  `CommandError::Storage` on database failures.
	 */
	embeddingActiveSet: (vendor: string, modelId: string) => typedError<null, CommandError>(__TAURI_INVOKE("embedding_active_set", { vendor, modelId })),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	embeddingActiveClear: () => typedError<boolean, CommandError>(__TAURI_INVOKE("embedding_active_clear")),
	/**
	 *  # Errors
	 *  Returns `CommandError::Storage` on database failures.
	 */
	reposList: () => typedError<RepoRecordTs[], CommandError>(__TAURI_INVOKE("repos_list")),
	/**
	 *  # Errors
	 *  `InvalidRepoPath` if canonicalize fails, `NotAGitRepo` if `<path>/.git`
	 *  doesn't exist, `DuplicateRepo` on UNIQUE violation, `Storage` otherwise.
	 */
	reposRegister: (path: string, displayName: string | null) => typedError<RepoRecordTs, CommandError>(__TAURI_INVOKE("repos_register", { path, displayName })),
	/**
	 *  # Errors
	 *  `InvalidUuid` if `repo_id` doesn't parse, `UnknownRepo` if the repo
	 *  is not registered, `InvalidRepoTargetBranch` if a non-empty branch does
	 *  not resolve locally, `Storage` otherwise.
	 */
	codeSetRepoTargetBranch: (repoId: string, targetBranch: string | null) => typedError<RepoRecordTs, CommandError>(__TAURI_INVOKE("code_set_repo_target_branch", { repoId, targetBranch })),
	/**
	 *  # Errors
	 *  `InvalidUuid` if `repo_id` doesn't parse, `Storage` otherwise.
	 */
	reposDelete: (repoId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("repos_delete", { repoId })),
	/**
	 *  # Errors
	 *  `InvalidUuid` if `repo_id` doesn't parse, `UnknownRepo` if the repo
	 *  is not registered for the sentinel owner, `Storage` otherwise.
	 */
	reposErase: (repoId: string) => typedError<RepoEraseReceiptTs, CommandError>(__TAURI_INVOKE("repos_erase", { repoId })),
	/**
	 *  Persist or return the active ingestion run, then kick the driver.
	 * 
	 *  # Errors
	 *  `UnknownRepo` if the repo is not registered; `InvalidUuid` if the id
	 *  does not parse; `Storage` on database failures.
	 */
	repoIngestStart: (repoId: string, maxCommits: number | null) => typedError<RepoIngestionRunTs, CommandError>(__TAURI_INVOKE("repo_ingest_start", { repoId, maxCommits })),
	/**
	 *  Return the active ingestion run for a repo, if any.
	 * 
	 *  # Errors
	 *  `InvalidUuid` if the id does not parse; `Storage` on database failures.
	 */
	repoIngestStatus: (repoId: string) => typedError<{
	run_id: string,
	repo_id: string,
	status: RunStatus,
	stage: RunStage,
	commits_emitted: number,
	files_emitted: number,
	chunks_emitted: number,
	chunks_reused: number,
	chunks_tombstoned: number,
	ast_edges_emitted: number,
	abstractions_emitted: number,
	embeddings_landed: number,
	citations_emitted: number,
	error_message: string | null,
	started_at: string,
	updated_at: string,
	finished_at: string | null,
} | null, CommandError>(__TAURI_INVOKE("repo_ingest_status", { repoId })),
	/**
	 *  Subscribe to current run snapshot plus live events for a repo.
	 * 
	 *  # Errors
	 *  `InvalidUuid` if the id does not parse; `Storage` on database failures.
	 */
	repoIngestSubscribe: (repoId: string, onEvent: Channel<RepoIngestEventTs>) => typedError<null, CommandError>(__TAURI_INVOKE("repo_ingest_subscribe", { repoId, onEvent })),
	payloadTypesAnchor: () => __TAURI_INVOKE<PayloadTypesAnchor_Serialize>("payload_types_anchor"),
	perfLog: (entries: PerfEntry[]) => __TAURI_INVOKE<void>("perf_log", { entries }),
	perfLogField: (entries: FieldEntry[]) => __TAURI_INVOKE<void>("perf_log_field", { entries }),
};

/* Types */
export type AuthoredByTs = "any" | "self_author" | "other";

export type BindInferenceTierTs = {
	owner: Owner,
	tier: ModelTierTs,
	target_ref: string,
};

export type BundledRecipeTs = {
	slug: string,
	flavor_id: string,
};

export type ChangeEvent = {
	seq: string,
	owner: Owner,
	kind: ChangeEventKind,
	/**
	 *  `Some(...)` when an in-process personality authored this event;
	 *  `None` for external/event-source ingestions.
	 */
	authoring_personality_instance_id?: string | null,
	/**
	 *  Wake-chain depth at the time the row was authored. `0` for
	 *  external events; `max(provenance.depth) + 1` for personality
	 *  authoring (capped per `MAX_WAKE_CHAIN_DEPTH`).
	 */
	wake_chain_depth?: number,
};

export type ChangeEventKind = ({ EntityAppend: {
	entity_kind: EntityKind,
	entity: EntityRef,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	supersedes: EntityRef | null,
} }) & { EdgeAppend?: never } | ({ EdgeAppend: {
	edge_id: string,
	relation: string,
	source: EntityRef,
	target: EntityRef,
} }) & { EntityAppend?: never };

export type CitationMappingHint = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
};

export type CitedObjectHint = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	content_hash: [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number],
};

/**
 *  Code chunk Fact. The "which blob this chunk belongs to" relation is
 *  carried by the substrate citation (shared `cited_object_id` with the
 *  parent `file-revision-v1` Fact, keyed by blob content hash) — no
 *  embedded `MemoryId` parent FK in the payload. See docs/11
 *  §"Three-layer model".
 */
export type CodeChunkV1 = {
	repo_id: string,
	file_path: string,
	chunk_index: number,
	text: string,
	language: string | null,
	chunk_type: string,
	byte_range_start: number,
	byte_range_end: number,
	line_range_start: number,
	line_range_end: number,
	state: FileState,
};

/**
 *  Errors returned from settings Tauri commands. Variants flatten
 *  the underlying `SettingsError` / `ConfigError` shapes into
 *  frontend-friendly typed payloads.
 */
export type CommandError = 
// Settings storage failed.
{ kind: "storage"; data: {
	message: string,
} } | 
// Two `[[embedding.models]]` rows share the same `(vendor, model_id)`.
{ kind: "duplicate_embedding_model"; data: {
	model_ref: EmbeddingModelRef,
} } | 
// The active embedding model is not registered in `[[embedding.models]]`.
{ kind: "unknown_embedding_model"; data: {
	model_ref: EmbeddingModelRef,
} } | 
// Config file could not be read.
{ kind: "config_io"; data: {
	path: string,
	message: string,
} } | 
// Config file could not be written.
{ kind: "config_save_io"; data: {
	path: string,
	message: string,
} } | 
// Config TOML did not parse or contains unknown fields.
{ kind: "config_parse"; data: {
	message: string,
} } | 
// Config TOML could not be serialized.
{ kind: "config_serialize"; data: {
	message: string,
} } | 
/**
 *  CHECK constraint violation in PG signals Rust-to-SQL drift.
 *  User cannot fix this from settings UI; report as a bug.
 */
{ kind: "invariant"; data: {
	message: string,
} } | 
// Repo path does not exist or cannot be canonicalized.
{ kind: "invalid_repo_path"; data: {
	path: string,
	reason: string,
} } | 
// Repo path is not a Git worktree.
{ kind: "not_a_git_repo"; data: {
	path: string,
} } | 
// Repo canonical path is already registered.
{ kind: "duplicate_repo"; data: {
	canonical_path: string,
} } | 
// Repo id does not belong to a registered repo.
{ kind: "unknown_repo"; data: {
	repo_id: string,
} } | 
// Repo target branch does not resolve to a local branch.
{ kind: "invalid_repo_target_branch"; data: {
	repo_id: string,
	target_branch: string,
	reason: string,
} } | 
// UUID string did not parse.
{ kind: "invalid_uuid"; data: {
	value: string,
} } | 
// Local secret store could not load or save a secret.
{ kind: "secret_store"; data: {
	message: string,
} };

export type DetectedHarnessTs = {
	path: string,
	version: string,
};

export type EdgeRow = {
	id: string,
	relation: string,
	relation_class: string,
	source: EntityRef,
	target: EntityRef,
	owner: Owner,
	payload: number[],
};

/**
 *  Embedding capability axes. `dim` is the vector size — boot-time
 *  mismatch against the storage migration's vector column is fatal.
 *  `matryoshka` indicates whether the model produces nested-prefix
 *  embeddings (caller may truncate without re-embedding).
 */
export type EmbedCaps = {
	dim: number,
	matryoshka: boolean,
};

// A single embedding model entry.
export type EmbeddingModelRecord = {
	vendor: string,
	model_id: string,
	base_url: string,
	caps: EmbedCaps,
	secret_ref?: string | null,
};

// Reference to an embedding model by `(vendor, model_id)`.
export type EmbeddingModelRef = {
	vendor: string,
	model_id: string,
};

export type EntityKind = "Fact" | "Abstraction" | "Perspective" | "Goal";

/**
 *  Endpoint of an Edge or supersedes target. Sum type matching
 *  `change_event` columns: a memory or a goal.
 */
export type EntityRef = ({ Memory: MemoryId }) & { Goal?: never } | ({ Goal: GoalId }) & { Memory?: never };

/**
 *  Subset of docs/14's `ErrorCode` exercised in M1. Additional
 *  variants land with the verbs that raise them.
 */
export type ErrorCode = "AuthRequired" | "Forbidden" | "UnknownSchema" | "AlreadyIngested" | "IdempotencyConflict" | "NotFound" | "InvalidArgument" | "RecipeInvalid" | "RecipeNotFound" | "ToolNotRegistered" | "InferenceTargetMissing" | "TierUnbound" | "TargetRefConflict" | "TargetInUse" | "TriggerConflict" | "DuplicateTriggerInRequest" | "GooseCliUnavailable" | "Internal";

export type EventDraft = {
	source_id: SourceId,
	source_batch_id: SourceBatchId,
	owner: Owner,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	payload: number[],
	observed_at: string,
	occurred_at: string,
	cited_object: CitedObjectHint,
	citation_mapping: CitationMappingHint,
};

export type EventHistoryRequest = {
	owner: Owner,
	limit: number,
	before: string | null,
};

export type EventHistoryResponse = {
	events: ChangeEvent[],
	seq_high_water: string | null,
};

/**
 *  BLAKE3-32 ContentHash of (source_id, owner, payload).
 *  Per docs/07 §"ID types" — events use ContentHash for
 *  re-receipt dedup, not UUIDv7.
 */
export type EventId = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type EventIngestOutcome = {
	event_id: EventId,
	memory_id: MemoryId,
	change_event_seq: string,
	/**
	 *  True iff the same `event_id` was already ingested.
	 *  docs/14 §EventIngest: "replay is silently a no-op."
	 */
	idempotent_replay: boolean,
};

export type ExecutionModeTs = "substrate_only" | "workspace";

export type FieldEntry = {
	cmd: string,
	field_path: string,
};

export type FileRevisionV1 = FileRevisionV1_Serialize | FileRevisionV1_Deserialize;

export type FileRevisionV1_Deserialize = {
	repo_id: string,
	file_path: string,
	language: string | null,
	content_sha256: string,
	size_bytes: number,
	indexed_commit_sha: string,
	state: FileState,
};

export type FileRevisionV1_Serialize = {
	repo_id: string,
	file_path: string,
	language: string | null,
	content_sha256: string,
	size_bytes: number,
	indexed_commit_sha: string,
	state: FileState,
};

export type FileState = "Present" | "Tombstone";

export type GoalAuthorship = "User" | { System: SystemOrigin } | "External";

export type GoalDraft = {
	owner: Owner,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	title: string,
	text: string,
	payload: number[],
	state: GoalState,
	parent_goal_ids: GoalId[],
	supersedes_goal_id: GoalId | null,
	authorship: GoalAuthorship,
	request_id: string,
};

export type GoalId = string;

export type GoalReactivateTs = {
	owner: Owner,
	goal_id: string,
	target_personality_id: string | null,
};

export type GoalRow = {
	id: GoalId,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	owner: Owner,
	title: string,
	text: string,
	state: GoalState,
	parent_goal_ids: GoalId[],
	supersedes: GoalId | null,
	payload: number[],
};

export type GoalScopeTs = "none" | "trigger_goal_assigned";

export type GoalState = "Proposed" | "Active" | "Paused" | "Achieved" | "Abandoned" | "Rejected";

export type GoalWriteOutcome = {
	goal_id: GoalId,
	change_event_seq: string,
	/**
	 *  True when the same `(owner, request_id)` existed and the
	 *  body matched — see docs/14 §GoalWrite.
	 */
	idempotent_replay: boolean,
};

export type GroupId = string;

export type IndexReportTs = {
	commits_emitted: number,
	commits_replayed: number,
	files_present_emitted: number,
	files_tombstoned: number,
	chunks_emitted: number,
	chunks_reused: number,
	chunks_tombstoned: number,
};

export type InferenceTargetConfigTs = { kind: "local_cli" } & (LocalCliConfigTs) | { kind: "remote_model" } & (RemoteModelConfigTs);

export type InferenceTargetTs = {
	target_ref: string,
	config: InferenceTargetConfigTs,
	created_at: string,
	updated_at: string,
};

export type InferenceTierBindingTs = {
	tier: ModelTierTs,
	target_ref: string,
};

export type IngestProgressTs = {
	commit_index: number,
	total_commits: number,
	commit_sha: string,
	commits_emitted: number,
	commits_replayed: number,
	chunks_emitted: number,
	chunks_reused: number,
};

export type InstantiatePersonalityOutcomeTs = {
	instance_id: string,
};

export type InstantiatePersonalityTs = {
	owner: Owner,
	display_name: string,
	purpose: string,
};

export type ListInferenceTargetsTs = {
	owner: Owner,
};

export type ListInferenceTierBindingsTs = {
	owner: Owner,
};

export type ListOwnerRecipesTs = {
	owner: Owner,
};

export type ListPersonalityInstancesTs = {
	owner: Owner,
	include_tombstoned?: boolean,
};

export type ListWakeInvocationsTs = {
	owner: Owner,
	personality_instance_id: string,
	wake_entry_id: string | null,
	limit: number,
};

export type LocalCliConfigTs = {
	command: string,
	profile: string | null,
	env_overrides: ([string, string])[],
};

export type McpConnectionTs = {
	url: string | null,
	token: string,
	authorization_header: string,
	listening: boolean,
};

export type McpToolTs = {
	name: string,
	description: string,
	flavor_id: string,
};

export type MemoryId = string;

/**
 *  Snapshot of a memory row. Goal rows have their own shape
 *  (M2+); not modelled here.
 */
export type MemoryRow = {
	id: MemoryId,
	kind: EntityKind,
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	owner: Owner,
	/**
	 *  CBOR projection of the sidecar row, populated by storage at read
	 *  time. Empty when the schema has no sidecar or when an
	 *  identity-only query mode is added.
	 *  Wire-only field — never persisted (docs/07).
	 */
	payload: number[],
};

export type ModelId = string;

export type ModelTierTs = "fast" | "standard" | "deep";

export type OperatorId = string;

export type OperatorKind = "AtoGoal";

export type OrgId = string;

/**
 *  Owner carries principal (access scope) and org_id (billing unit).
 *  org_id is NOT part of the access predicate (AGENTS.md invariant 4).
 */
export type Owner = {
	principal: Principal,
	org_id: OrgId,
};

export type OwnerRecipeTs = {
	filename: string,
	modified_at: string | null,
};

export type OwnerRecipesListingTs = {
	root_path: string,
	recipes: OwnerRecipeTs[],
};

export type PayloadKind = "Fact" | "Abstraction" | "Perspective" | "Goal" | 
/**
 *  Typed sidecar for an edge row, keyed on `edge_id`. See
 *  `EdgePayload` (docs/03 §EdgePayload) and the relation registry
 *  (docs/02 §"Relation registry").
 */
"Edge" | "CitedObject" | "CitationMapping";

/**
 *  Anchors flavor payload types in generated TypeScript bindings.
 *  The command is never used by the UI; Specta exports types through
 *  command signatures, so optional fields keep this cheap if invoked.
 */
export type PayloadTypesAnchor = PayloadTypesAnchor_Serialize | PayloadTypesAnchor_Deserialize;

/**
 *  Anchors flavor payload types in generated TypeScript bindings.
 *  The command is never used by the UI; Specta exports types through
 *  command signatures, so optional fields keep this cheap if invoked.
 */
export type PayloadTypesAnchor_Deserialize = {
	file_revision_v1: FileRevisionV1_Deserialize | null,
	code_chunk_v1: CodeChunkV1 | null,
};

/**
 *  Anchors flavor payload types in generated TypeScript bindings.
 *  The command is never used by the UI; Specta exports types through
 *  command signatures, so optional fields keep this cheap if invoked.
 */
export type PayloadTypesAnchor_Serialize = {
	file_revision_v1: FileRevisionV1_Serialize | null,
	code_chunk_v1: CodeChunkV1 | null,
};

export type PerfEntry = {
	kind: string,
	name: string,
	dur_ms: number,
	bytes: number | null,
};

export type PersonalityInstanceId = string;

export type PersonalityInstanceTs = {
	owner: Owner,
	personality_instance_id: string,
	current_root_perspective_memory_id: string,
	display_name: string,
	status: string,
	wake_entries: WakeEntryTs[],
};

export type PersonalityRootFilter = 
/**
 *  Include only active root/self Perspective rows. Non-root
 *  Perspectives are unaffected.
 */
"ActiveOnly" | 
/**
 *  Include inactive, tombstoned, and orphan root/self Perspective
 *  rows when they otherwise match the query.
 */
"IncludeInactive";

export type Principal = ({ User: UserId }) & { Group?: never } | ({ Group: GroupId }) & { User?: never };

export type ProducesTs = {
	schema_ids: string[],
	relation_ids: string[],
};

export type PromptVersion = string;

export type ProtocolError = {
	code: ErrorCode,
	message: string,
	request_id: string | null,
};

/**
 *  One core-generic Query request. Flavor-typed filters
 *  per docs/14 §"Query" land when the first flavor crate
 *  registers a sidecar (M3+).
 */
export type QueryRequest = {
	owner: Owner,
	entity_kind: EntityKind | null,
	schema_id: SchemaId | null,
	supersession: SupersessionStatus,
	tombstones?: TombstoneFilter,
	personality_roots?: PersonalityRootFilter,
	limit: number,
	/**
	 *  Include typed payload bytes in returned rows. Broad graph snapshots can
	 *  set this false and hydrate selected IDs later.
	 */
	include_payloads?: boolean,
	// Identity-keyed hydration for Subscribe-driven row fetches.
	memory_ids?: MemoryId[],
	goal_ids?: GoalId[],
	edge_ids?: string[],
};

export type QueryResponse = {
	memories: MemoryRow[],
	goals: GoalRow[],
	edges: EdgeRow[],
	/**
	 *  docs/14 §"Cursor & resume" — None when the store has
	 *  not yet recorded any change events.
	 */
	seq_high_water: string | null,
};

export type RegisterInferenceTargetOutcomeTs = {
	target_ref: string,
	idempotent_replay: boolean,
};

export type RegisterInferenceTargetTs = {
	owner: Owner,
	target_ref: string,
	config: InferenceTargetConfigTs,
};

export type RelationTs = {
	relation_id: string,
	flavor_id: string,
	class: string,
	typed: boolean,
};

export type RemoteModelConfigTs = {
	vendor: string,
	dialect: string,
	model_id: string,
	credentials_ref: string | null,
};

export type RemoveInferenceTargetOutcomeTs = {
	idempotent_replay: boolean,
};

export type RemoveInferenceTargetTs = {
	owner: Owner,
	target_ref: string,
};

export type RepoEraseReceiptTs = {
	repo_id: string,
	completed_at: string,
	facts_deleted: number,
	abstractions_deleted: number,
	edges_deleted: number,
	embeddings_deleted: number,
	events_deleted: number,
	citation_mappings_deleted: number,
	cited_objects_deleted: number,
	source_batches_deleted: number,
	f2a_rows_deleted: number,
	repo_record_deleted: boolean,
};

export type RepoIngestEventTs = { kind: "progress"; data: IngestProgressTs } | { kind: "snapshot"; data: RepoIngestionRunTs } | { kind: "done"; data: IndexReportTs } | { kind: "error"; data: {
	message: string,
} };

export type RepoIngestionRunTs = {
	run_id: string,
	repo_id: string,
	status: RunStatus,
	stage: RunStage,
	commits_emitted: number,
	files_emitted: number,
	chunks_emitted: number,
	chunks_reused: number,
	chunks_tombstoned: number,
	ast_edges_emitted: number,
	abstractions_emitted: number,
	embeddings_landed: number,
	citations_emitted: number,
	error_message: string | null,
	started_at: string,
	updated_at: string,
	finished_at: string | null,
};

export type RepoRecordTs = {
	repo_id: string,
	canonical_path: string,
	display_name: string,
	target_branch: string | null,
	has_been_polled: boolean,
	last_polled_at: string | null,
	created_at: string,
};

export type RunStage = "starting" | "facts" | "ast_edges" | "f2a" | "embeddings" | "done";

export type RunStatus = "queued" | "running" | "succeeded" | "failed";

export type SchemaId = string;

export type SchemaInfo = {
	schema_id: SchemaId,
	schema_version: SchemaVersion,
	kind: PayloadKind,
	filter_keys: string[],
	/**
	 *  Sidecar table identifier (qualified, e.g. `proxima_code.code_chunk_v1`)
	 *  when the payload trait declares one; `None` for `CitedObject` and
	 *  `CitationMapping` payloads which don't participate in F/A/P queries.
	 */
	sidecar_table: string | null,
	/**
	 *  Natural-key columns for stateful Fact schemas (docs/03 §Stateful
	 *  Fact schemas). Empty for stateless / non-Fact schemas. Drives the
	 *  head-by-natural-key SQL emission in `Query` heads-only mode.
	 */
	natural_key_columns: string[],
	// Build-time tombstone discriminator for stateful Fact schemas.
	tombstone: SchemaTombstone | null,
};

export type SchemaResponse = {
	schemas: SchemaInfo[],
};

export type SchemaTombstone = {
	column: string,
	value: string,
};

export type SchemaVersion = number;

export type SetWakeEntriesOutcomeTs = {
	active_entries: number,
};

export type SetWakeEntriesTs = {
	owner: Owner,
	personality_instance_id: string,
	entries: WakeEntryDraftTs[],
};

/**
 *  UUIDv7, declared by the source at emit time.
 *  See docs/01 §"The contract".
 */
export type SourceBatchId = string;

// Stable identifier of an Event Source. docs/07 §"ID types".
export type SourceId = string;

export type SubscribeRequest = {
	owner: Owner,
	/**
	 *  Resume cursor. Server returns events with `seq > since`.
	 *  `None` means "from the beginning of the change log".
	 */
	since: string | null,
};

export type SupersessionStatus = 
// Heads only — exclude rows that are superseded.
"HeadsOnly" | 
// Include superseded rows.
"IncludeSuperseded";

export type SystemOrigin = ({ Operator: {
	operator_id: OperatorId,
	operator_kind: OperatorKind,
	model_id: ModelId,
	prompt_version: PromptVersion,
	personality_instance_id: PersonalityInstanceId,
} }) & { Tool?: never } | ({ Tool: {
	tool_id: ToolId,
} }) & { Operator?: never };

export type TombstoneFilter = "PresentOnly" | "IncludeTombstoned";

export type TombstonePersonalityOutcomeTs = {
	status: string,
	idempotent_replay: boolean,
};

export type TombstonePersonalityTs = {
	owner: Owner,
	personality_instance_id: string,
};

export type ToolId = string;

export type TriggerKindTs = "on_memory" | "on_edge";

export type UserId = string;

export type WakeEntryDraftTs = {
	trigger_kind: TriggerKindTs,
	trigger_id: string,
	label: string,
	enabled: boolean,
	execution_mode: ExecutionModeTs,
	authored_by: AuthoredByTs,
	probability_promille: number,
	goal_scope: GoalScopeTs,
	recipe_ref: string,
	model_tier: ModelTierTs,
	inference_target_ref: string | null,
	substrate_tool_palette: string[],
	workspace_tool_palette: string[],
	max_rounds: number,
};

export type WakeEntryTs = {
	wake_entry_id: string,
	trigger_kind: TriggerKindTs,
	trigger_id: string,
	label: string,
	enabled: boolean,
	execution_mode: ExecutionModeTs,
	authored_by: AuthoredByTs,
	probability_promille: number,
	goal_scope: GoalScopeTs,
	recipe_ref: string,
	model_tier: ModelTierTs,
	inference_target_ref: string | null,
	substrate_tool_palette: string[],
	workspace_tool_palette: string[],
	max_rounds: number,
	disabled_reason: string | null,
};

export type WakeInvocationLogTs = {
	log_seq: number,
	at: string,
	phase: string,
	tool_id: string | null,
	status: string,
	duration_ms: number | null,
	message_tail: string | null,
};

export type WakeInvocationTs = {
	personality_instance_id: string,
	wake_entry_id: string,
	wake_entry_label: string,
	change_event_seq: string,
	status: string,
	started_at: string,
	finished_at: string | null,
	turn_count: number,
	cost_usd: number,
	recipe_sha256: string | null,
	resolved_inference_target_ref: string | null,
	failure_reason: string | null,
	exit_code: number | null,
	duration_ms: number | null,
	stdout_tail: string | null,
	stderr_tail: string | null,
	stdout_truncated: boolean,
	stderr_truncated: boolean,
	logs: WakeInvocationLogTs[],
};

export type WorkspaceToolTs = {
	id: string,
	description: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

