//! Proxima engine core.
pub mod auth;
pub mod cursor;
pub mod engine;
pub mod error;
pub mod flavor;
pub mod ids;
pub mod outbox;
pub mod owner;
pub mod payload;
pub mod storage;
pub mod verbs;

pub use auth::*;
pub use cursor::*;
pub use engine::*;
pub use error::*;
pub use flavor::*;
pub use ids::*;
pub use outbox::*;
pub use owner::*;
pub use payload::*;
pub use storage::*;

// Re-export verb modules for convenience.
pub use verbs::*;

// Re-export subscribe types explicitly for external use.
pub use verbs::subscribe::{ChangeEventStream, SubscribeRequest};

/// Expands to `&'static str` with the calling crate's name
/// prefixed. Per docs/08 §Schema namespacing.
///
/// `proxima_schema_id!("commit")` in a crate named
/// `proxima-code` evaluates to `"proxima-code/commit"`.
#[macro_export]
macro_rules! proxima_schema_id {
    ($short:literal) => {
        ::std::concat!(::std::env!("CARGO_PKG_NAME"), "/", $short)
    };
}

/// Build-time registration macro. v1 subset — supports
/// `fact_schemas`, `abstraction_schemas`, `perspective_schemas`.
/// Expands to a `pub fn register(registry: &mut FlavorRegistry)`
/// that performs runtime prefix checks and adds each schema.
///
/// Future verbs (sources, tools, operators, personalities,
/// relations, goal_schemas) land in M5+ as the underlying
/// systems materialize. Reject unknown keys at expansion time
/// to keep authors honest.
///
/// ```ignore
/// proxima_flavor! {
///     name = "proxima-code",
///     fact_schemas = [ CommitV1, FileChangeV1 ],
/// }
/// ```
#[macro_export]
macro_rules! proxima_flavor {
    (
        name = $name:literal
        $(, fact_schemas = [ $($fact:ty),* $(,)? ])?
        $(, abstraction_schemas = [ $($abs:ty),* $(,)? ])?
        $(, perspective_schemas = [ $($persp:ty),* $(,)? ])?
        $(,)?
    ) => {
        /// Generated by `proxima_flavor!`. Composite binaries
        /// call this once per linked flavor at startup.
        pub fn register(registry: &mut $crate::FlavorRegistry) {
            let expected_prefix: &str = ::std::concat!($name, "/");
            $($(
                {
                    use $crate::FactPayload;
                    let id = <$fact as FactPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "FactPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_fact_schema::<$fact>();
                }
            )*)?
            $($(
                {
                    use $crate::AbstractionPayload;
                    let id = <$abs as AbstractionPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "AbstractionPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_abstraction_schema::<$abs>();
                }
            )*)?
            $($(
                {
                    use $crate::PerspectivePayload;
                    let id = <$persp as PerspectivePayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "PerspectivePayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_perspective_schema::<$persp>();
                }
            )*)?
        }
    };
}
