#!/usr/bin/env bash
# Dump the schema that replaying the embedded migrations from an empty
# database produces — one file per source, so the composition boundary
# stays visible (docs/how-to/migrations.md):
#
#   schema.core.sql  what core alone provides (proxima_core, extensions)
#   schema.code.sql  what the code flavor adds (proxima_code only; its
#                    emitted foreign keys into proxima_core are the
#                    dependency direction, stated rather than implied)
#
# The ledger bookkeeping tables (public._sqlx_migrations*) are excluded from
# both: they record the replay, they are not what it produces.
#
# On-demand inspection only. Do not commit the output.
#
# Usage:
#   scripts/regen-schema-sql.sh <output-dir>
#
# Environment:
#   PROXIMA_SCHEMA_PG_URL  admin URL used to create/drop the scratch database
#                          (falls back to PROXIMA_TEST_PG_URL, then the local
#                          dev default postgres://proxima:proxima@localhost:5432/proxima)
#   PROXIMA_PG_DUMP        pg_dump command; its major version must be >= the
#                          server's. May be a compound command such as
#                          "docker exec -i <container> pg_dump" — in that case
#                          the URL must resolve identically inside the
#                          container.
set -euo pipefail
cd "$(dirname "$0")/.."

if [ "${1:-}" = "" ] || [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
  echo "usage: scripts/regen-schema-sql.sh <output-dir>" >&2
  exit 2
fi

ADMIN_URL="${PROXIMA_SCHEMA_PG_URL:-${PROXIMA_TEST_PG_URL:-postgres://proxima:proxima@localhost:5432/proxima}}"
PG_DUMP="${PROXIMA_PG_DUMP:-pg_dump}"
OUT_DIR="$1"

SCRATCH="proxima_schema_replay_$$"
SCRATCH_URL="${ADMIN_URL%/*}/${SCRATCH}"

psql "$ADMIN_URL" -v ON_ERROR_STOP=1 -q -c "CREATE DATABASE \"$SCRATCH\";"
trap 'psql "$ADMIN_URL" -q -c "DROP DATABASE IF EXISTS \"$SCRATCH\" WITH (FORCE);" >/dev/null' EXIT

cargo run -q -p proxima-dev-migrate -- --database-url "$SCRATCH_URL"

# Normalization: version banners, psql \restrict guards, and session SET
# preamble vary across pg_dump minor versions without describing schema.
normalize() {
  grep -vE '^(-- Dumped (from|by) |\\(un)?restrict |SET |SELECT pg_catalog\.set_config)'
}

mkdir -p "$OUT_DIR"
{
  echo "-- Generated by scripts/regen-schema-sql.sh — do not commit."
  echo "-- What core's migrations alone provide."
  $PG_DUMP --schema-only --no-owner --no-privileges \
    --exclude-schema=proxima_code \
    --exclude-table 'public._sqlx_migrations*' \
    "$SCRATCH_URL" | normalize
} > "$OUT_DIR/schema.core.sql"

{
  echo "-- Generated by scripts/regen-schema-sql.sh — do not commit."
  echo "-- What the code flavor's migrations add on top of core: the"
  echo "-- proxima_code schema only. Foreign keys into proxima_core are the"
  echo "-- flavor's dependency on core, stated explicitly."
  $PG_DUMP --schema-only --no-owner --no-privileges \
    --schema=proxima_code \
    "$SCRATCH_URL" | normalize
} > "$OUT_DIR/schema.code.sql"

echo "wrote $OUT_DIR/schema.core.sql and $OUT_DIR/schema.code.sql"
