//! Proxima engine core.
pub mod approval;
pub mod auth;
pub mod canonical_json;
pub mod citations;
pub mod cursor;
pub mod dependency;
pub mod embedding_settings;
pub mod engine;
pub mod error;
pub mod flavor;
pub mod harness;
pub mod ids;
pub mod inference;
pub mod inquiry;
pub mod intervention;
pub mod llm;
pub mod mcp;
pub mod models;
pub mod outbox;
pub mod owner;
pub mod payload;
pub mod payload_contract;
pub mod personality;
pub mod relation;
pub mod secrets;
pub mod storage;
pub mod verbs;
pub mod wake;
pub mod workspace_run;

pub use approval::*;
pub use auth::*;
pub use canonical_json::canonical_json;
pub use citations::*;
pub use cursor::*;
pub use dependency::*;
pub use embedding_settings::*;
pub use engine::*;
pub use error::*;
pub use flavor::*;
pub use ids::*;
pub use inference::{
    BindInferenceTierRequest, BindInferenceTierResponse, ChatGPTCodexConfig, InferenceTargetConfig,
    InferenceTargetKind, InferenceTargetRow, InferenceTierBindingRow, ListInferenceTargetsRequest,
    ListInferenceTierBindingsRequest, MistralChatConfig, OpenAIChatConfig, OpenAIResponsesConfig,
    RegisterInferenceTargetRequest, RegisterInferenceTargetResponse, RemoveInferenceTargetRequest,
    RemoveInferenceTargetResponse,
};
pub use inquiry::*;
pub use intervention::*;
pub use llm::*;
pub use mcp::{
    Handle, HandleTable, McpAuthorContext, McpCallFn, McpTool, McpToolCtx, McpToolDescriptor,
    McpToolError, MemoryHandleClass, OutputMode,
};
pub use models::*;
pub use outbox::*;
pub use owner::*;
pub use payload::*;
pub use payload_contract::assert_no_serde_json_value_fields;
pub use personality::workspace::{
    WorkspaceFinalizeInput, WorkspaceOutcome, WorkspacePrepareInput, WorkspacePreparedRun,
    WorkspaceRunRecord, WorkspaceRunner, WorkspaceRunnerError,
};
pub use personality::*;
pub use relation::*;
pub use secrets::*;
pub use storage::*;
pub use workspace_run::*;

// Re-export verb modules for convenience.
pub use verbs::*;

// Re-export subscribe types explicitly for external use.
pub use verbs::schema::FlavorRegistryFrozen;
pub use verbs::subscribe::{ChangeEventStream, SubscribeRequest};

/// Expands to `&'static str` with the calling crate's name
/// prefixed. Per docs/08 §Schema namespacing.
///
/// `proxima_schema_id!("commit")` in a crate named
/// `proxima-code` evaluates to `"proxima-code/commit"`.
#[macro_export]
macro_rules! proxima_schema_id {
    ($short:literal) => {
        ::std::concat!(::std::env!("CARGO_PKG_NAME"), "/", $short)
    };
}

/// Build-time registration macro. v1 subset — supports
/// `fact_schemas`, `abstraction_schemas`, `perspective_schemas`,
/// `goal_schemas`, `edge_schemas`, `relations`, `mcp_tools`.
/// Expands to a
/// `pub fn register(registry: &mut FlavorRegistry)` that performs
/// runtime prefix checks and adds each schema / relation.
///
/// `edge_schemas` registers `EdgePayload` impls; `relations`
/// registers `RelationDescriptor` literals — typed relations
/// must reference an edge schema also listed in `edge_schemas`,
/// cross-checked at `FlavorRegistry::freeze`.
///
/// Build-time owns the *capability vocabulary* (`LlmCaps`,
/// `EmbedCaps`) and operator `requires` declarations; specific
/// `(vendor, model_id)` bindings are runtime configuration, not
/// flavor authorship. New models plug in at runtime.
///
/// Future verbs (sources, operators) land as the
/// underlying systems materialize. Reject unknown keys at expansion
/// time to keep authors honest.
///
/// ```ignore
/// proxima_flavor! {
///     name = "proxima-code",
///     fact_schemas = [ CommitV1, FileChangeV1 ],
///     edge_schemas = [ EdgeCallsV1 ],
///     relations = [ RelationDescriptor::typed(
///         "proxima-code/calls",
///         RelationClass::Structural,
///         SchemaRef::new(SchemaId::new("proxima-code/calls".into()),
///                        SchemaVersion::new(1)),
///     ) ],
/// }
/// ```
///
#[macro_export]
macro_rules! proxima_flavor {
    (
        name = $name:literal
        $(, display_name = $display_name:literal)?
        $(, fact_schemas = [ $($fact:ty),* $(,)? ])?
        $(, abstraction_schemas = [ $($abs:ty),* $(,)? ])?
        $(, perspective_schemas = [ $($persp:ty),* $(,)? ])?
        $(, goal_schemas = [ $($goal:ty),* $(,)? ])?
        $(, edge_schemas = [ $($edge:ty),* $(,)? ])?
        $(, relations = [ $($rel:expr),* $(,)? ])?
        $(, mcp_tools = [ $($tool:ty),* $(,)? ])?
        $(, workspace_runner = $workspace_runner:ty)?
        $(, workspace_triggers = [ $($workspace_trigger_schema:literal),* $(,)? ])?
        $(, dependency_satisfaction_rules = [ $($dependency_rule:ty),* $(,)? ])?
        $(,)?
    ) => {
        /// Generated by `proxima_flavor!`. Composite binaries
        /// call this once per linked flavor at startup.
        pub fn register(registry: &mut $crate::FlavorRegistry) {
            #[allow(unused_variables)]
            let expected_prefix: &str = ::std::concat!($name, "/");
            {
                #[allow(unused_assignments, unused_mut)]
                let mut display_name: &str = $name;
                $(display_name = $display_name;)?
                let author: ::std::option::Option<::std::string::String> =
                    ::std::option_env!("CARGO_PKG_AUTHORS")
                        .filter(|s: &&str| !s.is_empty())
                        .map(|s: &str| {
                            s.split(':').next().unwrap_or(s).trim().to_string()
                        });
                registry.add_flavor($crate::FlavorDescriptor {
                    flavor_id: $name.to_string(),
                    display_name: display_name.to_string(),
                    package_version: ::std::env!("CARGO_PKG_VERSION").to_string(),
                    author,
                    provenance: $crate::FlavorProvenance::Builtin,
                });
            }
            $($(
                {
                    use $crate::FactPayload;
                    let id = <$fact as FactPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "FactPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_fact_schema::<$fact>();
                }
            )*)?
            $($(
                {
                    use $crate::AbstractionPayload;
                    let id = <$abs as AbstractionPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "AbstractionPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_abstraction_schema::<$abs>();
                }
            )*)?
            $($(
                {
                    use $crate::PerspectivePayload;
                    let id = <$persp as PerspectivePayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "PerspectivePayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_perspective_schema::<$persp>();
                }
            )*)?
            $($(
                {
                    use $crate::GoalPayload;
                    let id = <$goal as GoalPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "GoalPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_goal_schema::<$goal>();
                }
            )*)?
            $($(
                {
                    use $crate::EdgePayload;
                    let id = <$edge as EdgePayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "EdgePayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_edge_schema::<$edge>();
                }
            )*)?
            $($(
                {
                    let descriptor: $crate::RelationDescriptor = $rel;
                    assert!(
                        descriptor.relation.starts_with(expected_prefix),
                        "RelationDescriptor relation {:?} does not start with crate prefix {:?}",
                        descriptor.relation, expected_prefix,
                    );
                    registry.add_relation(descriptor);
                }
            )*)?
            $($(
                {
                    use $crate::McpTool;
                    let name = <$tool as McpTool>::NAME;
                    assert!(
                        name.starts_with(expected_prefix),
                        "McpTool::NAME {:?} does not start with crate prefix {:?}",
                        name, expected_prefix,
                    );
                    registry.add_mcp_tool::<$tool>($name);
                }
            )*)?
            $(
                {
                    use $crate::WorkspaceRunner;
                    let runner: ::std::sync::Arc<dyn WorkspaceRunner> =
                        ::std::sync::Arc::new(<$workspace_runner as ::std::default::Default>::default());
                    registry.add_workspace_runner($name, runner);
                }
            )?
            $($(
                {
                    let schema_id: &str = $workspace_trigger_schema;
                    assert!(
                        schema_id.starts_with(expected_prefix) || schema_id.starts_with("proxima-core/"),
                        "workspace trigger schema {:?} does not start with crate prefix {:?}",
                        schema_id, expected_prefix,
                    );
                    registry.add_workspace_trigger(schema_id);
                }
            )*)?
            $($(
                {
                    use $crate::DependencySatisfactionRule;
                    let rule: ::std::sync::Arc<dyn DependencySatisfactionRule> =
                        ::std::sync::Arc::new(<$dependency_rule as ::std::default::Default>::default());
                    let schema_id = rule.target_schema_id();
                    assert!(
                        schema_id.starts_with(expected_prefix) || schema_id.starts_with("proxima-core/"),
                        "DependencySatisfactionRule schema {:?} does not start with crate prefix {:?}",
                        schema_id, expected_prefix,
                    );
                    registry.add_dependency_satisfaction_rule(schema_id, rule);
                }
            )*)?
        }
    };
}
