//! Proxima engine core.
pub mod auth;
pub mod cursor;
pub mod engine;
pub mod error;
pub mod flavor;
pub mod ids;
pub mod mcp;
pub mod models;
pub mod operators;
pub mod outbox;
pub mod owner;
pub mod payload;
pub mod relation;
pub mod secrets;
pub mod storage;
pub mod verbs;

pub use auth::*;
pub use cursor::*;
pub use engine::*;
pub use error::*;
pub use flavor::*;
pub use ids::*;
pub use mcp::{
    Handle, HandleTable, McpAuthorContext, McpCallFn, McpTool, McpToolCtx, McpToolDescriptor,
    McpToolError,
};
pub use models::*;
pub use operators::*;
pub use outbox::*;
pub use owner::*;
pub use payload::*;
pub use relation::*;
pub use secrets::*;
pub use storage::*;

// Re-export verb modules for convenience.
pub use verbs::*;

// Re-export subscribe types explicitly for external use.
pub use verbs::subscribe::{ChangeEventStream, SubscribeRequest};

/// Expands to `&'static str` with the calling crate's name
/// prefixed. Per docs/08 §Schema namespacing.
///
/// `proxima_schema_id!("commit")` in a crate named
/// `proxima-code` evaluates to `"proxima-code/commit"`.
#[macro_export]
macro_rules! proxima_schema_id {
    ($short:literal) => {
        ::std::concat!(::std::env!("CARGO_PKG_NAME"), "/", $short)
    };
}

/// Build-time registration macro. v1 subset — supports
/// `fact_schemas`, `abstraction_schemas`, `perspective_schemas`,
/// `goal_schemas`, `edge_schemas`, `relations`, `mcp_tools`. Expands to a
/// `pub fn register(registry: &mut FlavorRegistry)` that performs
/// runtime prefix checks and adds each schema / relation.
///
/// `edge_schemas` registers `EdgePayload` impls; `relations`
/// registers `RelationDescriptor` literals — typed relations
/// must reference an edge schema also listed in `edge_schemas`,
/// cross-checked at `FlavorRegistry::freeze`.
///
/// Build-time owns the *capability vocabulary* (`LlmCaps`,
/// `EmbedCaps`) and operator `requires` declarations; specific
/// `(vendor, model_id)` bindings are runtime configuration, not
/// flavor authorship. New models plug in at runtime.
///
/// Future verbs (sources, operators, personalities) land as the
/// underlying systems materialize. Reject unknown keys at expansion
/// time to keep authors honest.
///
/// ```ignore
/// proxima_flavor! {
///     name = "proxima-code",
///     fact_schemas = [ CommitV1, FileChangeV1 ],
///     edge_schemas = [ EdgeCallsV1 ],
///     relations = [ RelationDescriptor::typed(
///         "proxima-code/calls",
///         RelationClass::Structural,
///         SchemaRef::new(SchemaId::new("proxima-code/calls".into()),
///                        SchemaVersion::new(1)),
///     ) ],
/// }
/// ```
#[macro_export]
macro_rules! proxima_flavor {
    (
        name = $name:literal
        $(, fact_schemas = [ $($fact:ty),* $(,)? ])?
        $(, abstraction_schemas = [ $($abs:ty),* $(,)? ])?
        $(, perspective_schemas = [ $($persp:ty),* $(,)? ])?
        $(, goal_schemas = [ $($goal:ty),* $(,)? ])?
        $(, edge_schemas = [ $($edge:ty),* $(,)? ])?
        $(, relations = [ $($rel:expr),* $(,)? ])?
        $(, mcp_tools = [ $($tool:ty),* $(,)? ])?
        $(,)?
    ) => {
        /// Generated by `proxima_flavor!`. Composite binaries
        /// call this once per linked flavor at startup.
        pub fn register(registry: &mut $crate::FlavorRegistry) {
            let expected_prefix: &str = ::std::concat!($name, "/");
            $($(
                {
                    use $crate::FactPayload;
                    let id = <$fact as FactPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "FactPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_fact_schema::<$fact>();
                }
            )*)?
            $($(
                {
                    use $crate::AbstractionPayload;
                    let id = <$abs as AbstractionPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "AbstractionPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_abstraction_schema::<$abs>();
                }
            )*)?
            $($(
                {
                    use $crate::PerspectivePayload;
                    let id = <$persp as PerspectivePayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "PerspectivePayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_perspective_schema::<$persp>();
                }
            )*)?
            $($(
                {
                    use $crate::GoalPayload;
                    let id = <$goal as GoalPayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "GoalPayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_goal_schema::<$goal>();
                }
            )*)?
            $($(
                {
                    use $crate::EdgePayload;
                    let id = <$edge as EdgePayload>::SCHEMA_ID;
                    assert!(
                        id.starts_with(expected_prefix),
                        "EdgePayload SCHEMA_ID {:?} does not start with crate prefix {:?}",
                        id, expected_prefix,
                    );
                    registry.add_edge_schema::<$edge>();
                }
            )*)?
            $($(
                {
                    let descriptor: $crate::RelationDescriptor = $rel;
                    assert!(
                        descriptor.relation.starts_with(expected_prefix),
                        "RelationDescriptor relation {:?} does not start with crate prefix {:?}",
                        descriptor.relation, expected_prefix,
                    );
                    registry.add_relation(descriptor);
                }
            )*)?
            $($(
                {
                    use $crate::McpTool;
                    let name = <$tool as McpTool>::NAME;
                    assert!(
                        name.starts_with(expected_prefix),
                        "McpTool::NAME {:?} does not start with crate prefix {:?}",
                        name, expected_prefix,
                    );
                    registry.add_mcp_tool::<$tool>($name);
                }
            )*)?
        }
    };
}
