name: "CLA Assistant"

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: write
  repository-projects: read

jobs:
  CLA-Assistant:
    if: github.event_name == 'pull_request_target' && (github.event.action == 'opened' || github.event.action == 'reopened' || github.event.action == 'synchronize')
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (!contains(github.event.pull_request.labels.*.name, 'CLA signed') || github.event.action == 'synchronize') && github.actor != 'cla-assistant' && github.actor != 'dependabot[bot]'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ASSISTANT_TOKEN }}
        with:
          path-to-signatures: '.github/cla/signatures.json'
          path-to-document: 'https://github.com/Aquilo-Solution-S/Proxima/blob/main/.github/cla/CLA.md'
          branch: 'main'
          allowlist: 'HeinrichvH,heinrichvonhelmolt,boreas-aquilo,cla-assistant,dependabot,dependabot[bot]'
